// prisma/seed.ts

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Starting seed...');

  // 1. Create Genres
  const genres = [
    { name: 'Fiksi Kontemporer', description: 'Contemporary fiction with modern setting' },
    { name: 'Romance', description: 'Love stories and romantic drama' },
    { name: 'Thriller', description: 'Mystery and suspense novels' },
    { name: 'Fantasi', description: 'Fantasy novels with imaginative elements' },
    { name: 'Young Adult', description: 'Novels for teenage readers' },
    { name: 'Inspiratif', description: 'Motivational and self-development novels' },
    { name: 'Horor', description: 'Horror and supernatural novels' },
    { name: 'Humor', description: 'Comedy and humorous novels' },
  ];

  console.log('📚 Creating genres...');
  const createdGenres = await Promise.all(
    genres.map((genre) =>
      prisma.genre.upsert({
        where: { name: genre.name },
        update: {},
        create: genre,
      })
    )
  );

  console.log(`✅ Created ${createdGenres.length} genres`);

  // 2. Create Books with Images
  const books = [
    // Fiksi Kontemporer
    {
      title: 'Laut Bercerita',
      writer: 'Leila S. Chudori',
      publisher: 'Kepustakaan Populer Gramedia',
      price: 95000,
      stockQuantity: 35,
      genreId: createdGenres.find((g) => g.name === 'Fiksi Kontemporer')!.id,
      image: 'https://cdn.gramedia.com/uploads/items/9786024246945.jpg',
      isbn: '978-6024246945',
      description: 'A novel about activists who disappeared during the New Order era. The sea becomes a silent witness to their struggles and sacrifices.',
      publicationYear: 2017,
      condition: 'new',
    },
    {
      title: 'Gadis Kretek',
      writer: 'Ratih Kumala',
      publisher: 'Gramedia Pustaka Utama',
      price: 89000,
      stockQuantity: 42,
      genreId: createdGenres.find((g) => g.name === 'Fiksi Kontemporer')!.id,
      image: 'https://cdn.gramedia.com/uploads/items/9786020333366_Gadis-Kretek.jpg',
      isbn: '978-6020333366',
      description: 'The story of Pak Raja, a legendary kretek maker searching for traces of a mysterious woman from his past.',
      publicationYear: 2012,
      condition: 'new',
    },
    {
      title: 'Pulang',
      writer: 'Leila S. Chudori',
      publisher: 'Kepustakaan Populer Gramedia',
      price: 98000,
      stockQuantity: 28,
      genreId: createdGenres.find((g) => g.name === 'Fiksi Kontemporer')!.id,
      image: 'https://cdn.gramedia.com/uploads/items/9786024241834_Pulang.jpg',
      isbn: '978-6024241834',
      description: 'A novel about political exiles after the 1965 tragedy and the longing to return home.',
      publicationYear: 2012,
      condition: 'like_new',
    },
    {
      title: 'Ronggeng Dukuh Paruk',
      writer: 'Ahmad Tohari',
      publisher: 'Gramedia Pustaka Utama',
      price: 92000,
      stockQuantity: 25,
      genreId: createdGenres.find((g) => g.name === 'Fiksi Kontemporer')!.id,
      image: 'https://cdn.gramedia.com/uploads/items/9786020822877.jpg',
      isbn: '978-6020822877',
      description: 'A trilogy about Srintil, a young ronggeng dancer, and her tragic love story set in a Javanese village.',
      publicationYear: 2003,
      condition: 'like_new',
    },
    {
      title: 'Orang-Orang Biasa',
      writer: 'Andrea Hirata',
      publisher: 'Bentang Pustaka',
      price: 88000,
      stockQuantity: 30,
      genreId: createdGenres.find((g) => g.name === 'Fiksi Kontemporer')!.id,
      image: 'https://cdn.gramedia.com/uploads/items/9786022914419_Orang-orang-Biasa.jpg',
      isbn: '978-6022914419',
      description: 'A story about extraordinary ordinary people who fight against injustice with courage and hope.',
      publicationYear: 2019,
      condition: 'new',
    },

    // Romance
    {
      title: 'Hujan',
      writer: 'Tere Liye',
      publisher: 'Gramedia Pustaka Utama',
      price: 75000,
      stockQuantity: 50,
      genreId: createdGenres.find((g) => g.name === 'Romance')!.id,
      image: 'https://cdn.gramedia.com/uploads/items/9786020822938.jpg',
      isbn: '978-6020822938',
      description: 'A love story of Lail and Esok separated by distance and time. The rain becomes a bridge of their memories.',
      publicationYear: 2016,
      condition: 'new',
    },
    {
      title: 'Perahu Kertas',
      writer: 'Dee Lestari',
      publisher: 'Bentang Pustaka',
      price: 85000,
      stockQuantity: 38,
      genreId: createdGenres.find((g) => g.name === 'Romance')!.id,
      image: 'https://cdn.gramedia.com/uploads/items/9789792248876_Perahu-Kertas.jpg',
      isbn: '978-9792248876',
      description: 'Kugy and Keenan have their own dreams. Their meeting changes everything forever.',
      publicationYear: 2009,
      condition: 'new',
    },
    {
      title: 'Dilan 1990',
      writer: 'Pidi Baiq',
      publisher: 'Pastel Books',
      price: 68000,
      stockQuantity: 55,
      genreId: createdGenres.find((g) => g.name === 'Romance')!.id,
      image: 'https://cdn.gramedia.com/uploads/items/9786021843239_Dilan-1990.jpg',
      isbn: '978-6021843239',
      description: 'The love story of Dilan and Milea in 1990 with a unique and witty romantic style.',
      publicationYear: 2014,
      condition: 'new',
    },
    {
      title: 'Rectoverso',
      writer: 'Dee Lestari',
      publisher: 'Bentang Pustaka',
      price: 79000,
      stockQuantity: 32,
      genreId: createdGenres.find((g) => g.name === 'Romance')!.id,
      image: 'https://cdn.gramedia.com/uploads/items/Rectoverso.jpg',
      isbn: '978-9799102577',
      description: 'Eleven love stories with various perspectives on the meaning of true love.',
      publicationYear: 2008,
      condition: 'like_new',
    },
    {
      title: 'Seperti Dendam, Rindu Harus Dibayar Tuntas',
      writer: 'Eka Kurniawan',
      publisher: 'Gramedia Pustaka Utama',
      price: 89000,
      stockQuantity: 26,
      genreId: createdGenres.find((g) => g.name === 'Romance')!.id,
      image: 'https://cdn.gramedia.com/uploads/items/9786020314716.jpg',
      isbn: '978-6020314716',
      description: 'A tale of revenge and unrequited love that spans years, filled with violence and passion.',
      publicationYear: 2014,
      condition: 'new',
    },
    {
      title: 'Rembulan Tenggelam di Wajahmu',
      writer: 'Tere Liye',
      publisher: 'Gramedia Pustaka Utama',
      price: 72000,
      stockQuantity: 40,
      genreId: createdGenres.find((g) => g.name === 'Romance')!.id,
      image: 'https://cdn.gramedia.com/uploads/items/9786020377872_Rembulan-Tenggelam-di-Wajahmu.jpg',
      isbn: '978-6020377872',
      description: 'A touching love story about sacrifice, hope, and the power of sincere love.',
      publicationYear: 2017,
      condition: 'new',
    },

    // Thriller
    {
      title: 'Pembunuhan di Kota Z',
      writer: 'Eka Aryani',
      publisher: 'Gramedia Pustaka Utama',
      price: 82000,
      stockQuantity: 25,
      genreId: createdGenres.find((g) => g.name === 'Thriller')!.id,
      image: 'https://cdn.gramedia.com/uploads/picture_meta/2023/3/31/eowqc6oqj8srhbwpbfh4xd.jpg',
      isbn: '978-6020652436',
      description: 'A series of mysterious murders in a small town reveals dark secrets from the past.',
      publicationYear: 2020,
      condition: 'new',
    },
    {
      title: 'Cantik Itu Luka',
      writer: 'Eka Kurniawan',
      publisher: 'Gramedia Pustaka Utama',
      price: 98000,
      stockQuantity: 30,
      genreId: createdGenres.find((g) => g.name === 'Thriller')!.id,
      image: 'https://cdn.gramedia.com/uploads/items/9786020314723_Cantik_Itu_Luka.jpg',
      isbn: '978-6020314723',
      description: 'An epic novel about a family curse spanning from colonial times to post-independence.',
      publicationYear: 2002,
      condition: 'new',
    },
    {
      title: 'Lelaki Harimau',
      writer: 'Eka Kurniawan',
      publisher: 'Gramedia Pustaka Utama',
      price: 85000,
      stockQuantity: 28,
      genreId: createdGenres.find((g) => g.name === 'Thriller')!.id,
      image: 'https://cdn.gramedia.com/uploads/items/9786020314730.jpg',
      isbn: '978-6020314730',
      description: 'A story of Margio who murders his father, intertwined with mystical elements and dark secrets.',
      publicationYear: 2004,
      condition: 'new',
    },

    // Fantasi
    {
      title: 'Bumi',
      writer: 'Tere Liye',
      publisher: 'Gramedia Pustaka Utama',
      price: 79000,
      stockQuantity: 48,
      genreId: createdGenres.find((g) => g.name === 'Fantasi')!.id,
      image: 'https://cdn.gramedia.com/uploads/items/9786020331423_Bumi.jpg',
      isbn: '978-6020331423',
      description: 'Raib, Seli, and Ali discover a parallel world full of adventures and special powers.',
      publicationYear: 2014,
      condition: 'new',
    },
    {
      title: 'Bulan',
      writer: 'Tere Liye',
      publisher: 'Gramedia Pustaka Utama',
      price: 85000,
      stockQuantity: 40,
      genreId: createdGenres.find((g) => g.name === 'Fantasi')!.id,
      image: 'https://cdn.gramedia.com/uploads/items/9786020382999_Bulan.jpg',
      isbn: '978-6020382999',
      description: 'The adventure continues to the Moon clan filled with mystery and magical powers.',
      publicationYear: 2015,
      condition: 'new',
    },
    {
      title: 'Matahari',
      writer: 'Tere Liye',
      publisher: 'Gramedia Pustaka Utama',
      price: 89000,
      stockQuantity: 36,
      genreId: createdGenres.find((g) => g.name === 'Fantasi')!.id,
      image: 'https://cdn.gramedia.com/uploads/items/9786024553081_Matahari.jpg',
      isbn: '978-6024553081',
      description: 'The final battle against Miss Selena to save the parallel world.',
      publicationYear: 2016,
      condition: 'new',
    },
    {
      title: 'Bintang',
      writer: 'Tere Liye',
      publisher: 'Gramedia Pustaka Utama',
      price: 92000,
      stockQuantity: 34,
      genreId: createdGenres.find((g) => g.name === 'Fantasi')!.id,
      image: 'https://cdn.gramedia.com/uploads/items/9786024811389_Bintang.jpg',
      isbn: '978-6024811389',
      description: 'New mysteries emerge as the adventure in the parallel world continues with greater challenges.',
      publicationYear: 2017,
      condition: 'new',
    },
    {
      title: 'Ceros dan Batozar',
      writer: 'Tere Liye',
      publisher: 'Gramedia Pustaka Utama',
      price: 88000,
      stockQuantity: 32,
      genreId: createdGenres.find((g) => g.name === 'Fantasi')!.id,
      image: 'https://cdn.gramedia.com/uploads/items/9786024811518_Ceros-dan-Batozar.jpg',
      isbn: '978-6024811518',
      description: 'The epic conclusion of the Bumi series with the greatest battle ever faced.',
      publicationYear: 2018,
      condition: 'new',
    },

    // Young Adult
    {
      title: 'Resign!',
      writer: 'Almira Bastari',
      publisher: 'Gramedia Pustaka Utama',
      price: 72000,
      stockQuantity: 45,
      genreId: createdGenres.find((g) => g.name === 'Young Adult')!.id,
      image: 'https://cdn.gramedia.com/uploads/items/9786020645117_Resign.jpg',
      isbn: '978-6020645117',
      description: 'A fresh graduate faces the reality of the working world with all its drama and dilemmas.',
      publicationYear: 2020,
      condition: 'new',
    },
    {
      title: 'Critical Eleven',
      writer: 'Ika Natassa',
      publisher: 'Gramedia Pustaka Utama',
      price: 78000,
      stockQuantity: 38,
      genreId: createdGenres.find((g) => g.name === 'Young Adult')!.id,
      image: 'https://cdn.gramedia.com/uploads/items/9786020320540_Critical-Eleven.jpg',
      isbn: '978-6020320540',
      description: 'Ale and Anya meet on a plane. 11 minutes that change their lives forever.',
      publicationYear: 2015,
      condition: 'like_new',
    },
    {
      title: 'Dilan 1991',
      writer: 'Pidi Baiq',
      publisher: 'Pastel Books',
      price: 70000,
      stockQuantity: 48,
      genreId: createdGenres.find((g) => g.name === 'Young Adult')!.id,
      image: 'https://cdn.gramedia.com/uploads/items/9786021843246_Dilan-1991.jpg',
      isbn: '978-6021843246',
      description: 'The continuation of Dilan and Milea\'s love story with new challenges and sweeter moments.',
      publicationYear: 2015,
      condition: 'new',
    },
    {
      title: 'Koala Kumal',
      writer: 'Raditya Dika',
      publisher: 'Gagas Media',
      price: 58000,
      stockQuantity: 42,
      genreId: createdGenres.find((g) => g.name === 'Young Adult')!.id,
      image: 'https://cdn.gramedia.com/uploads/items/koala-kumal.jpg',
      isbn: '978-6025118203',
      description: 'Dika\'s hilarious attempts at finding true love, filled with awkward moments and comedy.',
      publicationYear: 2015,
      condition: 'new',
    },

    // Inspiratif
    {
      title: 'Hafalan Shalat Delisa',
      writer: 'Tere Liye',
      publisher: 'Republika',
      price: 65000,
      stockQuantity: 33,
      genreId: createdGenres.find((g) => g.name === 'Inspiratif')!.id,
      image: 'https://cdn.gramedia.com/uploads/items/img20220606_14361639.jpg',
      isbn: '978-9793062754',
      description: 'A touching story of Delisa, a young girl who survived the Aceh tsunami and remains cheerful.',
      publicationYear: 2005,
      condition: 'good',
    },
    {
      title: 'Negeri 5 Menara',
      writer: 'Ahmad Fuadi',
      publisher: 'Gramedia Pustaka Utama',
      price: 75000,
      stockQuantity: 40,
      genreId: createdGenres.find((g) => g.name === 'Inspiratif')!.id,
      image: 'https://cdn.gramedia.com/uploads/items/9789792248920_Negeri-5-Menara.jpg',
      isbn: '978-9792248920',
      description: 'An inspiring story of Alif Fikri and his friends at boarding school with dreams as high as towers.',
      publicationYear: 2009,
      condition: 'new',
    },
    {
      title: 'Laskar Pelangi',
      writer: 'Andrea Hirata',
      publisher: 'Bentang Pustaka',
      price: 85000,
      stockQuantity: 35,
      genreId: createdGenres.find((g) => g.name === 'Inspiratif')!.id,
      image: 'https://cdn.gramedia.com/uploads/items/9789797809867.jpg',
      isbn: '978-9797809867',
      description: 'The struggle of 10 children from Belitung pursuing education amid limitations.',
      publicationYear: 2005,
      condition: 'like_new',
    },
    {
      title: 'Sang Pemimpi',
      writer: 'Andrea Hirata',
      publisher: 'Bentang Pustaka',
      price: 82000,
      stockQuantity: 32,
      genreId: createdGenres.find((g) => g.name === 'Inspiratif')!.id,
      image: 'https://cdn.gramedia.com/uploads/items/9789797809874.jpg',
      isbn: '978-9797809874',
      description: 'The sequel to Laskar Pelangi, following Ikal and Arai\'s dreams of studying in Paris.',
      publicationYear: 2006,
      condition: 'new',
    },
    {
      title: 'Ranah 3 Warna',
      writer: 'Ahmad Fuadi',
      publisher: 'Gramedia Pustaka Utama',
      price: 78000,
      stockQuantity: 36,
      genreId: createdGenres.find((g) => g.name === 'Inspiratif')!.id,
      image: 'https://cdn.gramedia.com/uploads/items/9789792294415_Ranah-3-Warna.jpg',
      isbn: '978-9792294415',
      description: 'Alif\'s journey continues as he faces new challenges while maintaining his dreams and values.',
      publicationYear: 2011,
      condition: 'new',
    },

    // Horor
    {
      title: 'Misteri Dendam Pocong',
      writer: 'S. Mara Gd',
      publisher: 'Tiga Serangkai',
      price: 58000,
      stockQuantity: 22,
      genreId: createdGenres.find((g) => g.name === 'Horor')!.id,
      image: 'https://cdn.gramedia.com/uploads/items/9786024423506.jpg',
      isbn: '978-6024423506',
      description: 'The terror of a pocong haunting a village due to unresolved grudges from the past.',
      publicationYear: 2018,
      condition: 'new',
    },
    {
      title: 'KKN di Desa Penari',
      writer: 'SimpleMan',
      publisher: 'Gramedia Pustaka Utama',
      price: 75000,
      stockQuantity: 50,
      genreId: createdGenres.find((g) => g.name === 'Horor')!.id,
      image: 'https://cdn.gramedia.com/uploads/items/9786020638560_KKN-di-Desa-Penari.jpg',
      isbn: '978-6020638560',
      description: 'The terrifying experience of students doing community service who break taboos in a mysterious village.',
      publicationYear: 2019,
      condition: 'new',
    },
    {
      title: 'Danur',
      writer: 'Risa Saraswati',
      publisher: 'Bukune',
      price: 68000,
      stockQuantity: 38,
      genreId: createdGenres.find((g) => g.name === 'Horor')!.id,
      image: 'https://cdn.gramedia.com/uploads/items/9786029290486.jpg',
      isbn: '978-6029290486',
      description: 'A true story about Risa\'s childhood friendship with ghost children who become her best friends.',
      publicationYear: 2012,
      condition: 'like_new',
    },
    {
      title: 'Terowongan Casablanca',
      writer: 'Eka Kurniawan',
      publisher: 'Gramedia Pustaka Utama',
      price: 72000,
      stockQuantity: 28,
      genreId: createdGenres.find((g) => g.name === 'Horor')!.id,
      image: 'https://cdn.gramedia.com/uploads/items/9786024246556.jpg',
      isbn: '978-6024246556',
      description: 'A collection of dark and eerie short stories exploring supernatural phenomena and human psychology.',
      publicationYear: 2017,
      condition: 'new',
    },

    // Humor
    {
      title: 'Kambing Jantan',
      writer: 'Raditya Dika',
      publisher: 'Gagas Media',
      price: 52000,
      stockQuantity: 40,
      genreId: createdGenres.find((g) => g.name === 'Humor')!.id,
      image: 'https://cdn.gramedia.com/uploads/items/9789797809546.jpg',
      isbn: '978-9797809546',
      description: 'A collection of hilarious stories about Raditya Dika\'s puppy love experiences and heartbreaks.',
      publicationYear: 2005,
      condition: 'good',
    },
    {
      title: 'Manusia Setengah Salmon',
      writer: 'Raditya Dika',
      publisher: 'Gagas Media',
      price: 55000,
      stockQuantity: 35,
      genreId: createdGenres.find((g) => g.name === 'Humor')!.id,
      image: 'https://cdn.gramedia.com/uploads/items/manusia_setengah_salmon_cov.jpg',
      isbn: '978-9797945909',
      description: 'The continuation of Raditya Dika\'s absurd adventures with various hilarious daily incidents.',
      publicationYear: 2011,
      condition: 'like_new',
    },
    {
      title: 'Cinta Brontosaurus',
      writer: 'Raditya Dika',
      publisher: 'Gagas Media',
      price: 54000,
      stockQuantity: 38,
      genreId: createdGenres.find((g) => g.name === 'Humor')!.id,
      image: 'https://cdn.gramedia.com/uploads/items/cinta-brontosaurus.jpg',
      isbn: '978-6028519410',
      description: 'More funny stories about love and relationships told in Raditya Dika\'s unique comedic style.',
      publicationYear: 2006,
      condition: 'good',
    },
    {
      title: 'Marmut Merah Jambu',
      writer: 'Raditya Dika',
      publisher: 'Gagas Media',
      price: 56000,
      stockQuantity: 33,
      genreId: createdGenres.find((g) => g.name === 'Humor')!.id,
      image: 'https://cdn.gramedia.com/uploads/items/marmut-merah-jambu.jpg',
      isbn: '978-6028519434',
      description: 'A humorous love story that teaches us to laugh at ourselves and enjoy life\'s absurdities.',
      publicationYear: 2010,
      condition: 'like_new',
    },
  ];

  console.log('📖 Creating books...');
  let createdCount = 0;
  
  for (const book of books) {
    try {
      await prisma.book.upsert({
        where: { title: book.title },
        update: {},
        create: book,
      });
      createdCount++;
      console.log(`  ✓ Added: ${book.title}`);
    } catch (error) {
      console.error(`  ✗ Failed to add: ${book.title}`, error);
    }
  }

  console.log(`✅ Created ${createdCount}/${books.length} books`);
  console.log('🎉 Seed completed successfully!');
}

main()
  .catch((e) => {
    console.error('❌ Seed failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });// prisma/seed.ts